name: reusable_workflow_caller_from_another_repo
on:
  workflow_dispatch:

jobs:
  run-npm-test4-from-another-repo:
    uses: didaRatsimba/to_be_called_by_action/.github/workflows/to_be_called.yaml
    with:
      specific-version: 14
