name: npm cache with matrix
on:
  workflow_dispatch:

jobs:
  run-npm-install-with-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        node: [14, lts/*]
        include:
          - os: ubuntu-latest
            node: 12
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name : setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: cache node_modules install
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.os}}-nodematrix-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-node-
      - name: run install
        shell: bash
        run: |
          npm install

  run-npm-test-with-cache:
    needs: run-npm-install-with-cache
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04 ]
        node: [ 14, lts/* ]
        include:
          - os: ubuntu-latest
            node: 12
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cache node_modules test
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.os}}-nodematrix-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-node-
      - name : setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: run test
        shell: bash
        run: |
          npm test
